In [1]:
from sklearn.datasets import fetch_20newsgroups
import pandas as pd

In [2]:
categories=['rec.sport.baseball','rec.sport.hockey']
sports_dataset=fetch_20newsgroups(subset='train',shuffle=True,random_state=42,categories=categories)

In [3]:
print(sports_dataset['data'][2])

From: rudy@netcom.com (Rudy Wade)
Subject: Re: YANKKES 1 GAME CLOSER
Article-I.D.: netcom.rudyC52rBD.86w
Organization: Home of the Brave
Lines: 18

My god, hope we don't have to put up with this kind of junk all season!

In article <002251w.5.734117130@axe.acadiau.ca> 002251w@axe.acadiau.ca (JASON WALTER WORKS) writes:
>    The N.Y.Yankees, are now one game closer to the A.L.East pennant.  They
>clobbered Cleveland, 9-1, on a fine pitching performance by Key, and two
>homeruns by Tartabull(first M.L.baseball to go out this season), and a three

How many home runs by Tartabull?  Just 1, right, you must be thinking
of Dean Palmer or Juan Gonzalez (both of Texas) who each had 2 homers.

>run homer by Nokes.  For all of you who didn't pick Boggs in your pools,
>tough break, he had a couple hits, and drove in a couple runs(with many more

I don't know how many to follow, but he was 1 for 4.

> GO YANKS., Mattingly for g.glove, and MVP, and Abbot for Cy Young.

Spare us, please!

In [4]:
sports_dataset['target'][2]

np.int64(0)

In [5]:
sports_dataset['target_names']

['rec.sport.baseball', 'rec.sport.hockey']

In [6]:
labels=[sports_dataset.target_names[x].split(".")[-1] for x in sports_dataset['target'] ]
text=[text.strip() for text in sports_dataset['data']]
df=pd.DataFrame(zip(text,labels),columns=['prompt','completion'])

In [7]:
df.head()

                                              prompt completion
0  From: dougb@comm.mot.com (Doug Bank)\nSubject:...   baseball
1  From: gld@cunixb.cc.columbia.edu (Gary L Dare)...     hockey
2  From: rudy@netcom.com (Rudy Wade)\nSubject: Re...   baseball
3  From: monack@helium.gas.uug.arizona.edu (david...     hockey
4  Subject: Let it be Known\nFrom: <ISSBTL@BYUVM....   baseball

In [34]:
df['prompt'][0]

"From: dougb@comm.mot.com (Doug Bank)\nSubject: Re: Info needed for Cleveland tickets\nReply-To: dougb@ecs.comm.mot.com\nOrganization: Motorola Land Mobile Products Sector\nDistribution: usa\nNntp-Posting-Host: 145.1.146.35\nLines: 17\n\nIn article <1993Apr1.234031.4950@leland.Stanford.EDU>, bohnert@leland.Stanford.EDU (matthew bohnert) writes:\n\n|> I'm going to be in Cleveland Thursday, April 15 to Sunday, April 18.\n|> Does anybody know if the Tribe will be in town on those dates, and\n|> if so, who're they playing and if tickets are available?\n\nThe tribe will be in town from April 16 to the 19th.\nThere are ALWAYS tickets available! (Though they are playing Toronto,\nand many Toronto fans make the trip to Cleveland as it is easier to\nget tickets in Cleveland than in Toronto.  Either way, I seriously\ndoubt they will sell out until the end of the season.)\n\n-- \nDoug Bank                       Private Systems Division\ndougb@ecs.comm.mot.com          Motorola Communications Sector\ndougb@nwu.edu                   Schaumburg, Illinois\ndougb@casbah.acns.nwu.edu       708-576-8207"

In [8]:
from huggingface_hub import login

login()

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

In [9]:
from transformers import AutoTokenizer, DataCollatorForLanguageModeling

In [10]:
from datasets import load_dataset, Dataset

In [11]:
model_name = "Qwen/Qwen3-0.6B"
tokenizer = AutoTokenizer.from_pretrained(model_name)
dataset = Dataset.from_pandas(df)

def tokenize(batch):
    return tokenizer(
        batch["prompt"],
        truncation=True,
        max_length=512,
    )

dataset = dataset.map(tokenize, batched=True, remove_columns=dataset.column_names)
dataset = dataset.train_test_split(test_size=0.1)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/726 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

Map:   0%|          | 0/1197 [00:00<?, ? examples/s]

In [12]:
dataset

DatasetDict({
    train: Dataset({
        features: ['input_ids', 'attention_mask'],
        num_rows: 1077
    })
    test: Dataset({
        features: ['input_ids', 'attention_mask'],
        num_rows: 120
    })
})

In [13]:
dataset['train'][0]

{'input_ids': [3830,
  25,
  20425,
  811,
  12755,
  31,
  7712,
  520,
  1121,
  6751,
  838,
  930,
  12586,
  320,
  35,
  299,
  1266,
  340,
  13019,
  25,
  89918,
  14263,
  304,
  3395,
  320,
  1847,
  9853,
  6259,
  340,
  41574,
  25,
  93194,
  3822,
  198,
  16794,
  25,
  220,
  16,
  16,
  19,
  198,
  45,
  89340,
  12,
  81652,
  12,
  9296,
  25,
  10770,
  6751,
  838,
  930,
  12586,
  198,
  55,
  12,
  14373,
  11149,
  25,
  350,
  687,
  508,
  4366,
  220,
  16,
  13,
  16,
  10315,
  23,
  2533,
  8420,
  374,
  264,
  3395,
  315,
  1045,
  315,
  279,
  1007,
  12,
  558,
  2513,
  429,
  614,
  198,
  31057,
  279,
  89918,
  419,
  1042,
  4192,
  784,
  75175,
  13272,
  27223,
  867,
  11148,
  8276,
  50,
  5308,
  33497,
  4826,
  198,
  785,
  794,
  3757,
  594,
  43470,
  64150,
  50398,
  3200,
  702,
  1012,
  65302,
  553,
  198,
  95340,
  13,
  1913,
  12,
  558,
  11,
  279,
  64150,
  2765,
  279,
  22375,
  14489,
  2265,
  714,
  198,
  1847,
  9853,
  572,
  2686,
  6247,
  13,
  362,
  13169,
  553,
  584,
  7337,
  702,
  9575,
  279,
  198,
  24153,
  82,
  700,
  315,
  279,
  88296,
  3283,
  369,
  1753,
  315,
  279,
  1537,
  4279,
  315,
  198,
  1782,
  9396,
  436,
  77,
  320,
  11284,
  5099,
  66452,
  568,
  2379,
  614,
  6342,
  330,
  5117,
  1,
  3868,
  304,
  7482,
  198,
  4803,
  29513,
  11,
  75950,
  323,
  45366,
  1716,
  295,
  779,
  13,
  10964,
  19380,
  330,
  5117,
  698,
  34568,
  686,
  387,
  6342,
  304,
  279,
  20957,
  5832,
  304,
  69669,
  11,
  3043,
  13,
  3776,
  198,
  25762,
  54581,
  2684,
  16401,
  13,
  35698,
  18349,
  264,
  64150,
  6,
  5828,
  323,
  198,
  20521,
  291,
  432,
  323,
  14422,
  11030,
  304,
  279,
  794,
  3757,
  594,
  26774,
  22636,
  624,
  19810,
  279,
  5322,
  11,
  14632,
  7359,
  31162,
  429,
  279,
  64150,
  198,
  14387,
  470,
  311,
  794,
  3757,
  594,
  3055,
  279,
  13169,
  10335,
  624,
  18782,
  19595,
  44756,
  60345,
  83151,
  198,
  785,
  1532,
  41614,
  53718,
  614,
  1012,
  6088,
  553,
  11044,
  26803,
  1515,
  311,
  198,
  1782,
  32166,
  53718,
  23677,
  7321,
  13,
  2379,
  525,
  279,
  1172,
  11888,
  198,
  45,
  13485,
  2083,
  448,
  458,
  3693,
  89918,
  21597,
  11,
  323,
  614,
  1865,
  432,
  2797,
  198,
  20069,
  29630,
  311,
  3271,
  279,
  2083,
  311,
  14696,
  304,
  279,
  11888,
  22375,
  198,
  1336,
  78565,
  13,
  1096,
  6278,
  323,
  3271,
  702,
  3602,
  311,
  387,
  11792,
  553,
  279,
  89918,
  198,
  1983,
  5163,
  11,
  714,
  374,
  3601,
  311,
  1494,
  6707,
  518,
  279,
  4586,
  6438,
  198,
  258,
  3217,
  13,
  576,
  12641,
  304,
  279,
  3364,
  504,
  7607,
  30357,
  2566,
  1865,
  432,
  715,
  7422,
  279,
  10734,
  572,
  803,
  8014,
  304,
  279,
  19753,
  315,
  279,
  715,
  32,
  13485,
  19024,
  23943,
  553,
  23677,
  15278,
  11,
  4751,
  1091,
  20337,
  198,
  1782,
  220,
  20,
  21,
  4666,
  3840,
  315,
  279,
  89918,
  304,
  1532,
  41614,
  13,
  4710,
  785,
  53718,
  525,
  5023,
  304,
  6001,
  23449,
  448,
  45366,
  1716,
  295,
  779,
  198,
  3564,
  60150,
  323,
  525,
  3601,
  311,
  3271,
  1052,
  624,
  18782,
  20747,
  35,
  3919,
  1911,
  37657,
  5012,
  472,
  14419,
  40449,
  3928,
  3022,
  1964,
  28537,
  1162,
  711,
  198,
  6025,
  37687,
  429,
  807,
  1035,
  6815,
  862,
  52791,
  700,
  198,
  1055,
  3128,
  302,
  263,
  11,
  279,
  51882,
  36489,
  5497,
  862,
  3971,
  13,
  4710,
  785,
  36489,
  7228,
  279,
  3271,
  979,
  807,
  1053,
  429,
  807,
  1035,
  387,
  91943,
  198,
  49728,
  8922,
  10734,
  21445,
  504,
  220,
  17,
  15,
  1331,
  11532,
  311,
  2163,
  264,
  20403,
  26,
  323,
  807,
  198,
  86592,
  311,
  4332,
  448,
  458,
  6350,
  89918,
  476,
  358,
  13485,
  19024,
  382,
  6269,
  279,
  18542,
  75181,
  24651],
 'attention_mask': [1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1]}

In [14]:
data_collator = DataCollatorForLanguageModeling(tokenizer, mlm=False),

In [15]:
data_collator

(DataCollatorForLanguageModeling(tokenizer=Qwen2Tokenizer(name_or_path='Qwen/Qwen3-0.6B', vocab_size=151643, model_max_length=131072, padding_side='right', truncation_side='right', special_tokens={'eos_token': '<|im_end|>', 'pad_token': '<|endoftext|>'}, added_tokens_decoder={
 	151643: AddedToken("<|endoftext|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
 	151644: AddedToken("<|im_start|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
 	151645: AddedToken("<|im_end|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
 	151646: AddedToken("<|object_ref_start|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
 	151647: AddedToken("<|object_ref_end|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
 	151648: AddedToken("<|box_start|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
 	151649: AddedToken("<|box_end|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
 	151650: AddedToken("<|quad_start|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
 	151651: AddedToken("<|quad_end|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
 	151652: AddedToken("<|vision_start|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
 	151653: AddedToken("<|vision_end|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
 	151654: AddedToken("<|vision_pad|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
 	151655: AddedToken("<|image_pad|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
 	151656: AddedToken("<|video_pad|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
 	151657: AddedToken("<tool_call>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=False),
 	151658: AddedToken("</tool_call>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=False),
 	151659: AddedToken("<|fim_prefix|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=False),
 	151660: AddedToken("<|fim_middle|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=False),
 	151661: AddedToken("<|fim_suffix|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=False),
 	151662: AddedToken("<|fim_pad|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=False),
 	151663: AddedToken("<|repo_name|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=False),
 	151664: AddedToken("<|file_sep|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=False),
 	151665: AddedToken("<tool_response>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=False),
 	151666: AddedToken("</tool_response>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=False),
 	151667: AddedToken("<think>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=False),
 	151668: AddedToken("</think>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=False),
 }
 ), mlm=False, whole_word_mask=False, mlm_probability=0.15, mask_replace_prob=0.8, random_replace_prob=0.1, pad_to_multiple_of=None, return_tensors='pt', seed=None),)

In [16]:
from transformers import AutoModelForCausalLM, TrainingArguments, Trainer

model_name = "Qwen/Qwen3-0.6B"
model = AutoModelForCausalLM.from_pretrained(model_name, dtype="auto")

model.safetensors:   0%|          | 0.00/1.50G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/311 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie model.embed_tokens.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning

generation_config.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

In [17]:
model

Qwen3ForCausalLM(
  (model): Qwen3Model(
    (embed_tokens): Embedding(151936, 1024)
    (layers): ModuleList(
      (0-27): 28 x Qwen3DecoderLayer(
        (self_attn): Qwen3Attention(
          (q_proj): Linear(in_features=1024, out_features=2048, bias=False)
          (k_proj): Linear(in_features=1024, out_features=1024, bias=False)
          (v_proj): Linear(in_features=1024, out_features=1024, bias=False)
          (o_proj): Linear(in_features=2048, out_features=1024, bias=False)
          (q_norm): Qwen3RMSNorm((128,), eps=1e-06)
          (k_norm): Qwen3RMSNorm((128,), eps=1e-06)
        )
        (mlp): Qwen3MLP(
          (gate_proj): Linear(in_features=1024, out_features=3072, bias=False)
          (up_proj): Linear(in_features=1024, out_features=3072, bias=False)
          (down_proj): Linear(in_features=3072, out_features=1024, bias=False)
          (act_fn): SiLUActivation()
        )
        (input_layernorm): Qwen3RMSNorm((1024,), eps=1e-06)
        (post_attention_layernorm): Qwen3RMSNorm((1024,), eps=1e-06)
      )
    )
    (norm): Qwen3RMSNorm((1024,), eps=1e-06)
    (rotary_emb): Qwen3RotaryEmbedding()
  )
  (lm_head): Linear(in_features=1024, out_features=151936, bias=False)
)

In [20]:
args=TrainingArguments(
    output_dir="qwen3-finetuned",
    num_train_epochs=1,
    per_device_train_batch_size=2,
    gradient_accumulation_steps=8,
    gradient_checkpointing=True,
    bf16=True,
    learning_rate=2e-5,
    logging_steps=10,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
)

In [22]:
trainer = Trainer(
    model=model,
    args=args,
    train_dataset=da
     taset["train"],
    eval_dataset=dataset["test"],
    processing_class=tokenizer,
    data_collator=DataCollatorForLanguageModeling(tokenizer, mlm=False),
)

trainer.train()

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151643}.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=68, training_loss=3.051531707539278, metrics={'train_runtime': 1089.5205, 'train_samples_per_second': 0.989, 'train_steps_per_second': 0.062, 'total_flos': 1595569607147520.0, 'train_loss': 3.051531707539278, 'epoch': 1.0})

In [24]:
finetuned_model = AutoModelForCausalLM.from_pretrained("qwen3-finetuned/checkpoint-68")

Loading weights:   0%|          | 0/311 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie model.embed_tokens.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning

In [25]:
finetuned_model

Qwen3ForCausalLM(
  (model): Qwen3Model(
    (embed_tokens): Embedding(151936, 1024, padding_idx=151643)
    (layers): ModuleList(
      (0-27): 28 x Qwen3DecoderLayer(
        (self_attn): Qwen3Attention(
          (q_proj): Linear(in_features=1024, out_features=2048, bias=False)
          (k_proj): Linear(in_features=1024, out_features=1024, bias=False)
          (v_proj): Linear(in_features=1024, out_features=1024, bias=False)
          (o_proj): Linear(in_features=2048, out_features=1024, bias=False)
          (q_norm): Qwen3RMSNorm((128,), eps=1e-06)
          (k_norm): Qwen3RMSNorm((128,), eps=1e-06)
        )
        (mlp): Qwen3MLP(
          (gate_proj): Linear(in_features=1024, out_features=3072, bias=False)
          (up_proj): Linear(in_features=1024, out_features=3072, bias=False)
          (down_proj): Linear(in_features=3072, out_features=1024, bias=False)
          (act_fn): SiLUActivation()
        )
        (input_layernorm): Qwen3RMSNorm((1024,), eps=1e-06)
        (post_attention_layernorm): Qwen3RMSNorm((1024,), eps=1e-06)
      )
    )
    (norm): Qwen3RMSNorm((1024,), eps=1e-06)
    (rotary_emb): Qwen3RotaryEmbedding()
  )
  (lm_head): Linear(in_features=1024, out_features=151936, bias=False)
)

In [27]:
finetuned_model.vocab_size

151936

In [30]:

import math
eval_trainer = Trainer(
    model=finetuned_model,
    args=args,
    eval_dataset=dataset["test"],
    data_collator=DataCollatorForLanguageModeling(tokenizer, mlm=False),
)

metrics = eval_trainer.evaluate()
perplexity = math.exp(metrics["eval_loss"])

print(f"Perplexity: {perplexity}")
print(metrics)

Perplexity: 19.12770905396581
{'eval_loss': 2.9511380195617676, 'eval_model_preparation_time': 0.019, 'eval_runtime': 43.2069, 'eval_samples_per_second': 2.777, 'eval_steps_per_second': 0.347}

In [40]:
prompt = "From: SomeUser@example.com (Some User)\nSubject: Re: baseball"

# Encode the prompt and move to the model's device
inputs = tokenizer(prompt, return_tensors='pt')
input_ids = inputs['input_ids'].to(finetuned_model.device)
attention_mask = inputs['attention_mask'].to(finetuned_model.device)

# Generate text using the finetuned model
output = finetuned_model.generate(
    input_ids,
    attention_mask=attention_mask,
    max_length=200,
    num_return_sequences=1,
    do_sample=True,
    top_k=50,
    top_p=0.95,
    pad_token_id=tokenizer.eos_token_id
)

# Decode and print the generated text
generated_text = tokenizer.decode(output[0], skip_special_tokens=True)
print(generated_text)

From: SomeUser@example.com (Some User)
Subject: Re: baseball
Organization: Some Org
Lines: 28

In article <1993Apr23.122420.1331@uclab.ucl.ac.uk>, bob@uclab.ucl.ac.uk (Bob) writes:
>Well, I don't know where the game is.  It's not that the game isn't
>real, but it's not that I'm a fan.  I'm going to be a fan of the game
>on the next Saturday, but I'm not going to be a fan of the next one.

Let me know if you have any ideas of which team will win.  I'll be watching
the game on the TV next Saturday, but I'll be watching it on the radio
next Thursday (because I'm going to be watching it on the radio at 11:00
PM